### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by Oober** [Drugwash2/Equalizer2#1]
So, how to install the applet? Already built the ladspa version of Pulseaudio-equalizer from the source.

**Comment by Drugwash2** [comment]
Are you using the Cinnamon Desktop? This is an applet for Cinnamon.

To install just unpack the applet folder in ~/local/share/cinnamon/applets. Then open the Applets dialog from the panel, select the Equalizer 2 applet and enable it (click on the plus sign).

If that's not what you meant then please elaborate on your setup and what still is confusing to you.

**Comment by Oober** [comment]
Hi, thanks. Installed to Mint 21.1. Faced another issue, i'll open new thread.
