### ISSUE TITLE
Cannot change preset

### ISSUE THREAD

**Issue by Oober** [Drugwash2/Equalizer2#2]
Cannot change the preset. The presets exist in the applet but trying to change them makes nothing.

Ideas?

**Comment by Drugwash2** [comment]
- is there any change in the presets list (i.e. does the newly selected get marked)?
- does changing the presets directly from the equalizer GUI make a difference as opposed to changing from the applet menu?
- is there any related error in Looking Glass' log?
- does enabling/disabling the equalizer work correctly (or at all)?

Unfortunately I haven't gotten to test this under the most recent Mint/Cinnamon so can't say if there is some issue specific to those.  My system is Mint 19.2 and it works correctly. It might take a while before I get to test in 21.x.

**Comment by Oober** [comment]
- No, the newly selected doesn't get marked.
- Changing the presets directly from pulseaudio-equalizer-gtk work normally. From the applet they don't.
- Found these errors from Melange log (right after installing the applet and trying to change the preset), but I don't know if these are relevant:
```
error t=2023-03-11T22:14:04Z Can't convert non-null pointer to JS value
error t=2023-03-11T22:14:04Z Error inspecting path: w(5)
```
- Enabling / disabling the eq from the applet works.

**Comment by Drugwash2** [comment]
Thank you. It's not much but it's a starting point. I'll see if I can run a VM with Mint 21.1 and check it there, maybe add some more debug.info. By the way: have you tried enabling debug in applet's preferences? Is there any useful info in the log with it enabled?
_(can't remember if the online version has it implemented, I run a slightly newer version here; darn bad memory...)_

**Comment by Oober** [comment]
It seems that there are no preferences for the applet. There is a mention of "preferences" but it contains nothing.

**Comment by Drugwash2** [comment]
Ah, that must be the previous version then. Sorry. I'll upload the current offline one in a bit, maybe it could help.

**Comment by Oober** [comment]
Installed v.1.2.4, no difference in functionality. I checked the debug option, where should I find the log? There are not anything interesting in Looking Glass' log.

**Comment by Drugwash2** [comment]
Yes, if anything the log should be in Looking Glass.

I tested briefly in virtual Mint 21.1 and for me changing presets works. However the tooltip behaves erratically, it only updates once, and the notification doesn't show up. So there are some problems.

Maybe the Equalizer version you're using has some parameters slightly changed? I'm using some older one found on the web since I was unable to build it myself. Or maybe code wasn't compatible with Ubuntu 18.04/Mint 19.x anymore - can't remember.

It will take some work as I'm swamped with other project right now. Can't promise anything.

**Comment by Oober** [comment]
> Maybe the Equalizer version you're using has some parameters slightly changed? I'm using some older one found on the web since I was unable to build it myself. Or maybe code wasn't compatible with Ubuntu 18.04/Mint 19.x anymore - can't remember.

I don't believe since the last change in the code seems to be 4 years ago or something. I grabbed the source from https://github.com/pulseaudio-equalizer-ladspa/equalizer .

**Comment by Drugwash2** [comment]
Mine is prebuilt, from some source mentioned in the readme of this applet. It was quite a mess at the time, can't remember exactly which worked. There seem to be at least two different versions - LADSPA and non-LADSPA. I do have the LADSPA and it seems to be slightly modified by me, sometime in december. Mostly GUI AFAIR.

I'm still very busy right now, this has to take a lower priority. Will get to it as soon as I can. Sorry about that.

**Comment by Drugwash2** [comment]
@Oober Could you please try v1.2.5, see if it fixes the issue? There were other minor bugs in the code that Cinnamon 5.4+ seemed to stumble into, maybe those were breaking the operation. Otherwise I'll have to think of something more... drastic.

**Comment by Oober** [comment]
The problem still exists in v1.2.5.

**Comment by Oober** [comment]
> Interestingly, with the virtual/testing **Mint 21.1** I have a different version, which is mentioned in applet's readme, downloaded from here: https://drive.google.com/file/d/1q2TEwMpEsqY4aTRzJCBIu8yr-weK1_XG/view Package name is `pulseaudio-equalizer-ladspa_3.0.2-1~eoan_all.deb`.
> 
> The applet works with both of these versions, in both Mint 19.2 and 21.1.
> 
> You may wanna uninstall the current version and try either of the aforementioned. If they fail too with this applet then I will have to implement some serious debug to find out what could go wrong with either version.

Thank you, the applet works with this version.

I think I have a solution for you. My previous version of pulseaudio eq was launched by commands 'pulseaudio-equalizer' and 'pulseaudio-equalizer-gtk'. This version runs with 'pulseaudio-equalizer-ladspa' and 'pulseaudio-equalizer-ladspa-gtk'. Maybe this makes your applet working erroneously.

**Comment by Drugwash2** [comment]
Ah, glad you finally got it working!

As for the two different commands - the aplet does check for all possible combinations of commands, including the old ones you mentioned, which do work in Mint 19, so there must have been something else. Maybe the parameters were different or something.

Yesterday I've been working on the applet and got it to ask the user for the preferred EQ version in case they have multiple versions installed. Thought that might've been your case. Didn't upload that version yet, it needs more checks and debug output implemented.

Do you by chance still remember where exactly the old EQ files were located? Did you build and install locally (/usr/local/bin), or in user's home, or some other path? Or, did you actually uninstall the old version or is it still there? This new applet build should detect it, maybe I could get enough debug info to find out what actually happens. I'll try to post it these days.

**Comment by Oober** [comment]
I don't recall the path of EQ files, I am sorry. It was installed by 'sudo ninja install' and yes - I unistalled it by 'sudo ninja uninstall'.

**Comment by Drugwash2** [comment]
No worries. If it's the same 3.0.2 version I'm using on Mint 19 then I should already know the paths. Strange that it didn't work for you though. Maybe that version has other deeper problems in Mint 21. Will copy the sources there, and try a build and install, see how it goes.

In the mean time enjoy the version that works for you. 😉

**Comment by Drugwash2** [comment]
I think I found the problem.
Most packages and the source at https://github.com/pulseaudio-equalizer-ladspa/equalizer use for presets a system path that contains `pulseaudio-equalizer-ladspa` while the executable remains as `pulseaudio-equalizer`. Since I had synchronized the presets path with the executable path the applet was only searching in `/usr/share/pulseaudio-equalizer/presets` or `/usr/local/share/pulseaudio-equalizer/presets` and it always failed.

Can't imagine how I didn't realize this earlier. Amazingly, in Mint 19 it always seemed to change preset visibly in the menu, but I guess it never actually changed it in the Equalizer itself. Oh the shame!

Will keep testing for a while, fixing whatever else may be wrong, and will post a new version as soon as it's ready.

**Comment by Drugwash2** [comment]
Version **1.3.0** uploaded. Fingers crossed!

**Comment by Oober** [comment]
I confirm that 1 3.0 works also with prebuilt version found from https://www.comoinstalarlinux.com/pulseaudio-equalizer-ladspa/ and version from
https://github.com/pulseaudio-equalizer-ladspa/equalizer. 

I leave using the latter one, I like it's better. 

Thank you!

**Comment by Drugwash2** [comment]
Ah, finally did it right. Whew! 😄

Have you tested the switching between EQs in the context menu? Had a few difficulties with it. Hopefully it works correctly for everybody.

Anyway, glad it finally works as it should. Thanks for the nudge. 😄

**Comment by Oober** [comment]
No, I didn't tested changing the EQ. I have had only one version installed at the same time.

**Comment by Drugwash2** [comment]
OK, no biggie. One is enough if it works. Enjoy. 😄
